language: haskell

ghc:
  - 7.8

before_install:
  - sudo apt-get update
  - sudo apt-get install update-manager-core
  - yes | sudo do-release-upgrade

install:
  - cabal update
  - cabal install alex happy MissingH data-ordlist split mtl
  - cabal install mtl

script:
  - cd scripts
  - ./main.sh

env:
  - TOWER_APP_NAME=arm-vm
