language: haskell

ghc:
  - 7.8

before_install:
  - sudo sed -i -e 's/precise/trusty/g' /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade

install:
  - cabal update
  - cabal install alex happy MissingH data-ordlist split mtl
  - cabal install mtl

script:
  - cd scripts
  - ./main.sh

env:
  - TOWER_APP_NAME=arm-vm
