sudo: false
language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gcc-arm-embedded
    - $HOME/.stack

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lib32ncurses5
      - libev-dev
      - gcc-4.8
      - libgmp3-dev
      - zlib1g-dev
      - make
      - libtinfo-dev
      - libncurses5-dev
      - realpath
      - python-pip
      - libxml2-utils
      - uboot-mkimage
      - python2.7-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p $HOME/.local/bin
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH="$HOME/.local/bin:$PATH"
  - stack --version
  # Download and unpack the ARM embedded toolchain
  - if [ ! -d $HOME/.gcc-arm-embedded/*/bin ];
    then
      mkdir -p $HOME/.gcc-arm-embedded;
      wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2 -O- | tar xjf - -C $HOME/.gcc-arm-embedded;
    fi
  - export PATH="$PWD:$(echo $HOME/.gcc-arm-embedded/*/bin):$PATH"
  - gcc --version
  - arm-none-eabi-gcc --version
  - export SMACCM_BRANCH=$TRAVIS_BRANCH

script:
  - cd scripts
  - ./main.sh
