sudo: false
language: java
jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - hvr-ghc
      - ubuntu-toolchain-r-test
    packages:
      - ghc-7.8.4
      - cabal-install-1.22
      - alex-3.1.4
      - happy-1.19.5
      - lib32ncurses5
      - libev-dev
      - gcc-4.8
      - libgmp3-dev
      - zlib1g-dev
      - make
      - libtinfo-dev
      - libncurses5-dev
      - realpath
      - python-pip
      - libxml2-utils
      - uboot-mkimage
      - python2.7-dev

before_install:
  - mkdir -p gcc-arm-embedded
  - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2 -O- | tar xjf - -C gcc-arm-embedded
  - export PATH="$PWD:$(echo $PWD/gcc-arm-embedded/*/bin):/opt/ghc/7.8.4/bin:/opt/cabal/1.22/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH"
  - gcc --version
  - arm-none-eabi-gcc --version
  - ghc --version
  - cabal --version
  - alex --version
  - happy --version

script:
  - cd scripts
  - ./main.sh
